github.com:
    users:
        VenkyKVP17:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: VenkyKVP17
