// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/agents/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agents/[name].get').default>>>>
    }
    '/api/agents/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agents/list.get').default>>>>
    }
    '/api/auth/google/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google/callback.get').default>>>>
    }
    '/api/dashboard/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stats.get').default>>>>
    }
    '/api/intelligence/context': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/intelligence/context.post').default>>>>
    }
    '/api/intelligence/query': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/intelligence/query.post').default>>>>
    }
    '/api/intelligence/telegram': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/intelligence/telegram.post').default>>>>
    }
    '/api/internal/index-vault': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/internal/index-vault.post').default>>>>
    }
    '/api/internal/report': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/internal/report.post').default>>>>
    }
    '/api/internal/sheets/roster': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/internal/sheets/roster.get').default>>>>
    }
    '/api/logs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logs.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logs.post').default>>>>
    }
    '/api/memory/ingest': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/memory/ingest.post').default>>>>
    }
    '/api/notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notify.post').default>>>>
    }
    '/api/nyx/aias': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/aias.get').default>>>>
    }
    '/api/nyx/analyze-finance': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/analyze-finance.post').default>>>>
    }
    '/api/nyx/briefing/catchup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/briefing/catchup.post').default>>>>
    }
    '/api/nyx/briefing/evening': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/briefing/evening.post').default>>>>
    }
    '/api/nyx/briefing/morning': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/briefing/morning.post').default>>>>
    }
    '/api/nyx/browse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/browse.post').default>>>>
    }
    '/api/nyx/compress': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/compress.post').default>>>>
    }
    '/api/nyx/dispatch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/dispatch.post').default>>>>
    }
    '/api/nyx/location': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/location.post').default>>>>
    }
    '/api/nyx/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/profile.get').default>>>>
    }
    '/api/nyx/queue-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/queue-status.get').default>>>>
    }
    '/api/nyx/queue': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/queue.get').default>>>>
    }
    '/api/nyx/save-media': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/save-media.post').default>>>>
    }
    '/api/nyx/search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/search.post').default>>>>
    }
    '/api/nyx/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/status.get').default>>>>
    }
    '/api/nyx/transcribe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nyx/transcribe.post').default>>>>
    }
    '/api/tasks/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].patch').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/api/telegram/handle-message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/telegram/handle-message.post').default>>>>
    }
    '/api/webhook/archived/github': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhook/archived/github.post').default>>>>
    }
    '/api/webhook/telegram': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhook/telegram.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}